Allows assertion on existence of fields when using fieldsFor... functions
joshgaber/NovaUnit pull request #58
Opened 2023-02-20 10:47 UTC by andypooletrioteca

When having fields defined in a fieldsForIndex, fieldsForUpdate, fieldsForCreate or fieldsForDetail functions the assertHasField was not enough. Added the methods assertHasIndexField, assertHasDetailField, assertHasUpdateField and assertHasCreationField to solve this problem.

2023-05-10 18:06 UTC, artim-ctrl requested changes

2023-05-10 18:06 UTC, artim-ctrl commented on src/Traits/FieldAssertions.php
> +    private function assertHasFieldIn(string $fieldsMethod, string $request, string $field, string $message = '')
it would be great to add return type here

2023-05-10 18:10 UTC, artim-ctrl commented
Hi, @joshgaber! What do you say about this? This functionality looks cool and would be useful for many, including me :)

2023-07-18 09:30 UTC, tobias-grasse commented on src/Traits/FieldAssertions.php
> +        return $this->assertHasFieldIn('fieldsForUpdate', ResourceCreateOrAttachRequest::class, $field, $message);
@andypooletrioteca Not sure if I'm missing something here, but it looks like the `$fieldsMethod` parameters should be flipped: `assertHasCreationField` → `fieldsForCreate`

2023-07-18 09:31 UTC, tobias-grasse commented on src/Traits/FieldAssertions.php
> +        return $this->assertHasFieldIn('fieldsForCreate', ResourceUpdateOrUpdateAttachedRequest::class, $field, $message);
@andypooletrioteca Same as [my comment above](https://github.com/joshgaber/NovaUnit/pull/58/files#r1266503808): `$fieldsMethod` parameter should be `fieldsForUpdate` in `assertHasUpdateField`.

2025-01-08 18:16 UTC, robertmarney commented
This project has been abandoned, its replacement can be found at https://github.com/qvelocity/novaunit, if this PR is still relevant please resubmit there.

2025-01-08 18:16 UTC, closed without merging