Fix ActionResponse return introduced with Nova > 4.24.0
joshgaber/NovaUnit pull request #59
Opened 2023-05-08 12:59 UTC by kichetof

Hello,

Nova 4.24.0 and up introduced a new `ActionResponse` class as return statement.

NovaUnit `MockActionResponse` expect an array instead of ActionResponse class.

This PR handle both types.

2023-05-11 15:30 UTC, Sergej-Tihonov requested changes
Looks good for me, beside a small copy mistake in the comment.

2023-05-11 15:30 UTC, Sergej-Tihonov commented on src/Actions/MockActionResponse.php
> +     * Asserts the handle response is of type "push".
... of type "**visit**".
Copy paste mistake.

2023-05-12 10:41 UTC, Sergej-Tihonov approved these changes

2023-05-12 10:41 UTC, Sergej-Tihonov approved these changes

2023-05-15 10:12 UTC, Sergej-Tihonov commented
@joshgaber can you take a look at this PR please.
It's a small and necessary change in regards of Nova 4.24.0 update.

2023-06-09 12:17 UTC, salvisb commented
Hi @joshgaber. Could review and merge this PR please?

2023-08-30 08:59 UTC, LorenzoAlu commented
I try this and it's work perfect thanks @kichetof ;)

2023-11-17 13:23 UTC, Xammie commented
It would be great if this could be merged :)

2024-09-24 20:54 UTC, robertmarney commented
Hey everyone,

As a head-up this package was marked as abandoned on packagist recently and has been replaced with a new fork (with @joshgaber's blessing) 

You can find it here: [Packagist](https://packagist.org/packages/quotevelocity/novaunit) and [GitHub](https://github.com/qvelocity/novaunit)

The latest release provides support for the new ActionResponse changes

2025-01-08 18:15 UTC, closed without merging